### PR TITLE
transferred over old repo

### PR DESCRIPTION
**Pull request by jorgenfj**

### CODE REVIEW

**Review by kluge7 — APPROVED** [review]
lgtm

**Comment by jorgenfj** [comment]
Not a fan of the use of " instead of ' in launch files. The convention for launch files appears to be '. Is it possible to make the formatter detect launch files to account for this?

**Review by Senja20 — APPROVED** [review]

**Comment by Senja20** [comment]
> Not a fan of the use of " instead of ' in launch files. The convention for launch files appears to be '. Is it possible to make the formatter detect launch files to account for this?

I have remote automatic formatting and left just a Python black checker. I also pass `--skip-string-normalization` as an argument, so it should not react to the quotes—temporary solution. I do not want to use non-black formatted on a single repo when we use the black formatter everywhere else. If black is an issue, maybe we should organize a migration to another formatter across the organization(?)

**Comment by kluge7** [comment]
> > Not a fan of the use of " instead of ' in launch files. The convention for launch files appears to be '. Is it possible to make the formatter detect launch files to account for this?
> 
> I have remote automatic formatting and left just a Python black checker. I also pass `--skip-string-normalization` as an argument, so it should not react to the quotes—temporary solution. I do not want to use non-black formatted on a single repo when we use the black formatter everywhere else. If black is an issue, maybe we should organize a migration to another formatter across the organization(?)

@Senja20 
I know that [The Ruff Formatter](https://docs.astral.sh/ruff/formatter/#the-ruff-formatter) could be an alternative to look into!

**Pull request merged**
